// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: spatialscale.proto

package spatialscalepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpatialQuery_RangeQuery_FullMethodName = "/spatialscale.SpatialQuery/RangeQuery"
)

// SpatialQueryClient is the client API for SpatialQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpatialQuery serves range queries over a preloaded QuadTree.
type SpatialQueryClient interface {
	// RangeQuery returns all points within the given bounding box,
	// optionally filtered to a single gene name.
	RangeQuery(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*RangeQueryResponse, error)
}

type spatialQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewSpatialQueryClient(cc grpc.ClientConnInterface) SpatialQueryClient {
	return &spatialQueryClient{cc}
}

func (c *spatialQueryClient) RangeQuery(ctx context.Context, in *RangeQueryRequest, opts ...grpc.CallOption) (*RangeQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeQueryResponse)
	err := c.cc.Invoke(ctx, SpatialQuery_RangeQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpatialQueryServer is the server API for SpatialQuery service.
// All implementations must embed UnimplementedSpatialQueryServer
// for forward compatibility.
//
// SpatialQuery serves range queries over a preloaded QuadTree.
type SpatialQueryServer interface {
	// RangeQuery returns all points within the given bounding box,
	// optionally filtered to a single gene name.
	RangeQuery(context.Context, *RangeQueryRequest) (*RangeQueryResponse, error)
	mustEmbedUnimplementedSpatialQueryServer()
}

// UnimplementedSpatialQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpatialQueryServer struct{}

func (UnimplementedSpatialQueryServer) RangeQuery(context.Context, *RangeQueryRequest) (*RangeQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeQuery not implemented")
}
func (UnimplementedSpatialQueryServer) mustEmbedUnimplementedSpatialQueryServer() {}
func (UnimplementedSpatialQueryServer) testEmbeddedByValue()                      {}

// UnsafeSpatialQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpatialQueryServer will
// result in compilation errors.
type UnsafeSpatialQueryServer interface {
	mustEmbedUnimplementedSpatialQueryServer()
}

func RegisterSpatialQueryServer(s grpc.ServiceRegistrar, srv SpatialQueryServer) {
	// If the following call panics, it indicates UnimplementedSpatialQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpatialQuery_ServiceDesc, srv)
}

func _SpatialQuery_RangeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialQueryServer).RangeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialQuery_RangeQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialQueryServer).RangeQuery(ctx, req.(*RangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpatialQuery_ServiceDesc is the grpc.ServiceDesc for SpatialQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpatialQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spatialscale.SpatialQuery",
	HandlerType: (*SpatialQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RangeQuery",
			Handler:    _SpatialQuery_RangeQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spatialscale.proto",
}
