// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: spatialscale.proto

package spatialscalepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinX          float64                `protobuf:"fixed64,1,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MinY          float64                `protobuf:"fixed64,2,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	MaxX          float64                `protobuf:"fixed64,3,opt,name=max_x,json=maxX,proto3" json:"max_x,omitempty"`
	MaxY          float64                `protobuf:"fixed64,4,opt,name=max_y,json=maxY,proto3" json:"max_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_spatialscale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_spatialscale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_spatialscale_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetMinX() float64 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *BoundingBox) GetMinY() float64 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *BoundingBox) GetMaxX() float64 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *BoundingBox) GetMaxY() float64 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

type RangeQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Box   *BoundingBox           `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"`
	// Optional exact gene name match. Empty string matches all genes.
	Gene          string `protobuf:"bytes,2,opt,name=gene,proto3" json:"gene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeQueryRequest) Reset() {
	*x = RangeQueryRequest{}
	mi := &file_spatialscale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeQueryRequest) ProtoMessage() {}

func (x *RangeQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spatialscale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeQueryRequest.ProtoReflect.Descriptor instead.
func (*RangeQueryRequest) Descriptor() ([]byte, []int) {
	return file_spatialscale_proto_rawDescGZIP(), []int{1}
}

func (x *RangeQueryRequest) GetBox() *BoundingBox {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *RangeQueryRequest) GetGene() string {
	if x != nil {
		return x.Gene
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_spatialscale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_spatialscale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_spatialscale_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RangeQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeQueryResponse) Reset() {
	*x = RangeQueryResponse{}
	mi := &file_spatialscale_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeQueryResponse) ProtoMessage() {}

func (x *RangeQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spatialscale_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeQueryResponse.ProtoReflect.Descriptor instead.
func (*RangeQueryResponse) Descriptor() ([]byte, []int) {
	return file_spatialscale_proto_rawDescGZIP(), []int{3}
}

func (x *RangeQueryResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_spatialscale_proto protoreflect.FileDescriptor

const file_spatialscale_proto_rawDesc = "" +
	"\n" +
	"\x12spatialscale.proto\x12\fspatialscale\"a\n" +
	"\vBoundingBox\x12\x13\n" +
	"\x05min_x\x18\x01 \x01(\x01R\x04minX\x12\x13\n" +
	"\x05min_y\x18\x02 \x01(\x01R\x04minY\x12\x13\n" +
	"\x05max_x\x18\x03 \x01(\x01R\x04maxX\x12\x13\n" +
	"\x05max_y\x18\x04 \x01(\x01R\x04maxY\"T\n" +
	"\x11RangeQueryRequest\x12+\n" +
	"\x03box\x18\x01 \x01(\v2\x19.spatialscale.BoundingBoxR\x03box\x12\x12\n" +
	"\x04gene\x18\x02 \x01(\tR\x04gene\"M\n" +
	"\x05Point\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"A\n" +
	"\x12RangeQueryResponse\x12+\n" +
	"\x06points\x18\x01 \x03(\v2\x13.spatialscale.PointR\x06points2_\n" +
	"\fSpatialQuery\x12O\n" +
	"\n" +
	"RangeQuery\x12\x1f.spatialscale.RangeQueryRequest\x1a .spatialscale.RangeQueryResponseB5Z3github.com/yaseer/spatialscale/proto/spatialscalepbb\x06proto3"

var (
	file_spatialscale_proto_rawDescOnce sync.Once
	file_spatialscale_proto_rawDescData []byte
)

func file_spatialscale_proto_rawDescGZIP() []byte {
	file_spatialscale_proto_rawDescOnce.Do(func() {
		file_spatialscale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spatialscale_proto_rawDesc), len(file_spatialscale_proto_rawDesc)))
	})
	return file_spatialscale_proto_rawDescData
}

var file_spatialscale_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spatialscale_proto_goTypes = []any{
	(*BoundingBox)(nil),        // 0: spatialscale.BoundingBox
	(*RangeQueryRequest)(nil),  // 1: spatialscale.RangeQueryRequest
	(*Point)(nil),              // 2: spatialscale.Point
	(*RangeQueryResponse)(nil), // 3: spatialscale.RangeQueryResponse
}
var file_spatialscale_proto_depIdxs = []int32{
	0, // 0: spatialscale.RangeQueryRequest.box:type_name -> spatialscale.BoundingBox
	2, // 1: spatialscale.RangeQueryResponse.points:type_name -> spatialscale.Point
	1, // 2: spatialscale.SpatialQuery.RangeQuery:input_type -> spatialscale.RangeQueryRequest
	3, // 3: spatialscale.SpatialQuery.RangeQuery:output_type -> spatialscale.RangeQueryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spatialscale_proto_init() }
func file_spatialscale_proto_init() {
	if File_spatialscale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spatialscale_proto_rawDesc), len(file_spatialscale_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spatialscale_proto_goTypes,
		DependencyIndexes: file_spatialscale_proto_depIdxs,
		MessageInfos:      file_spatialscale_proto_msgTypes,
	}.Build()
	File_spatialscale_proto = out.File
	file_spatialscale_proto_goTypes = nil
	file_spatialscale_proto_depIdxs = nil
}
