apiVersion: v1
kind: Service
metadata:
  name: spatialscale-server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: spatialscale-server
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
